// Les mots du métier, en une phrase chacun. Une infobulle (<Terme>) et le glossaire du guide lisent ce texte :
// une définition changée ici change partout.
//
// Deux langues : chaque entrée lit la langue au moment où on la lit (des accesseurs, pas des chaînes figées à
// l'import), si bien que `GLOSSAIRE[cle].terme` garde sa forme pour tous les appelants.
import { t } from "../i18n";

export interface Definition { readonly terme: string; readonly definition: string; readonly chapitre?: string }

function entree(terme: [string, string], definition: [string, string], chapitre?: string): Definition {
  return {
    get terme() { return t(terme[0], terme[1]); },
    get definition() { return t(definition[0], definition[1]); },
    chapitre,
  };
}

export const GLOSSAIRE = {
  ifc: entree(["IFC", "IFC"],
    ["Indemnité de fin de carrière : ce que l'employeur verse au salarié qui part en retraite, en mois de salaire, selon son ancienneté et la convention collective ou le régime de l'entreprise.",
     "End-of-service benefits: what the employer pays an employee who retires, in months of salary, according to length of service and the collective agreement or the company's own scheme."], "comprendre"),
  convention: entree(["Convention collective", "Collective agreement"],
    ["Le texte signé pour une branche (commerce, banques…) qui fixe le barème minimum de l'IFC. C'est le plancher : l'entreprise peut verser plus, jamais moins.",
     "The agreement signed for a sector (retail, banking…) that sets the minimum IFC scale. It is the floor: the company may pay more, never less."], "conventions"),
  regime: entree(["Régime", "Scheme"],
    ["Ce que VOTRE entreprise verse réellement : un accord, un usage, les contrats. Il peut être plus généreux que la convention, par catégorie de personnel.",
     "What YOUR company actually pays: an agreement, a custom, the employment contracts. It can be more generous than the collective agreement, by staff category."], "regime"),
  plancher: entree(["Plancher", "Floor"],
    ["Le minimum de la convention. À chaque ancienneté, le calcul retient le plus favorable du régime et de la convention.",
     "The collective agreement's minimum. At each length of service, the calculation keeps the more favourable of the scheme and the agreement."], "regime"),
  vapf: entree(["VAPF", "PVFB"],
    ["Valeur actuelle des prestations futures : l'IFC qui sera versée à chaque salarié, ramenée à aujourd'hui, pondérée par les chances qu'il soit encore là et en vie à la retraite.",
     "Present value of future benefits: the IFC each employee will be paid, discounted to today and weighted by the likelihood that they are still with the company, and alive, at retirement."], "comprendre"),
  dette: entree(["Dette actuarielle", "Actuarial liability"],
    ["La part de la VAPF déjà acquise par les années passées dans l'entreprise. C'est l'engagement à la date d'évaluation — ce qu'un assureur doit avoir en caisse pour être à jour.",
     "The share of the PVFB already earned through years spent in the company. It is the obligation at the valuation date — what an insurer must hold for the company to be fully funded."], "comprendre"),
  charge: entree(["Charge annuelle", "Annual service cost"],
    ["Ce que coûte une année de service de plus : les droits que les salariés acquièrent pendant l'exercice qui vient.",
     "What one more year of service costs: the entitlements employees earn during the coming financial year."], "comprendre"),
  fonds: entree(["Fonds constitué", "Accumulated fund"],
    ["L'argent déjà placé chez un assureur pour vos IFC. Il vous appartient et se retranche de ce qu'il reste à verser.",
     "The money already invested with an insurer for your IFC. It belongs to you and is deducted from what remains to be paid."], "financer"),
  cotisation_nette: entree(["Cotisation nette", "Net contribution"],
    ["Dette + charge − fonds : ce qu'il manque pour être à jour, avant les frais de l'assureur. Nulle si le fonds couvre déjà tout.",
     "Liability + service cost − fund: the shortfall to be fully funded, before the insurer's fees. Zero if the fund already covers everything."], "comprendre"),
  frais_cotisation: entree(["Frais sur cotisation", "Contribution fees"],
    ["La part de chaque versement que l'assureur garde pour sa gestion (4 % par défaut dans l'étude). La cotisation à verser = cotisation nette + ces frais.",
     "The share of each payment the insurer keeps for administration (4% by default in the study). Contribution to pay = net contribution + these fees."], "financer"),
  cotisation: entree(["Cotisation à verser", "Contribution to pay"],
    ["Le montant à verser à l'assureur, frais compris, pour que le fonds couvre la dette et la charge de l'année.",
     "The amount to pay the insurer, fees included, so that the fund covers the liability and the year's service cost."], "comprendre"),
  actualisation: entree(["Taux d'actualisation", "Discount rate"],
    ["Le taux qui ramène à aujourd'hui une somme payée dans des années. Plus il est haut, plus la dette paraît petite : c'est l'hypothèse la plus sensible.",
     "The rate that brings a sum paid years from now back to today's value. The higher it is, the smaller the liability looks: it is the most sensitive assumption."], "comprendre"),
  croissance: entree(["Croissance des salaires", "Salary growth"],
    ["La hausse annuelle supposée des salaires jusqu'à la retraite. L'IFC se calcule sur le salaire de fin de carrière, pas celui d'aujourd'hui.",
     "The assumed annual rise in salaries until retirement. The IFC is calculated on the final salary, not today's."], "comprendre"),
  turnover: entree(["Rotation du personnel", "Staff turnover"],
    ["La probabilité qu'un salarié quitte l'entreprise avant la retraite (démission, licenciement). Un départ avant la retraite ne coûte pas d'IFC.",
     "The probability that an employee leaves the company before retirement (resignation, dismissal). A departure before retirement costs no IFC."], "comprendre"),
  mortalite: entree(["Table de mortalité", "Mortality table"],
    ["Les probabilités de survie à chaque âge. L'étude utilise la table réglementaire CIMA (TV CIMA F).",
     "The probabilities of survival at each age. The study uses the CIMA regulatory table (TV CIMA F)."], "comprendre"),
  anciennete: entree(["Ancienneté", "Length of service"],
    ["Les années passées dans l'entreprise, calculées à partir de la date d'embauche.",
     "The years spent in the company, counted from the hiring date."], "personnel"),
  taux_garanti: entree(["Taux garanti", "Guaranteed rate"],
    ["Le rendement minimum que l'assureur s'engage à servir sur le fonds, chaque année.",
     "The minimum return the insurer undertakes to credit to the fund each year."], "financer"),
  participation: entree(["Participation aux bénéfices", "Profit sharing"],
    ["La part des produits financiers au-delà du taux garanti que l'assureur reverse au fonds (par exemple 85 %).",
     "The share of investment income above the guaranteed rate that the insurer credits back to the fund (for example 85%)."], "financer"),
  cout_net: entree(["Coût net actualisé", "Net present cost"],
    ["Ce que coûte une offre sur l'horizon choisi, ramené à aujourd'hui, fonds restant déduit. Il sert à comparer les offres entre elles ; il peut être négatif.",
     "What an offer costs over the chosen horizon, discounted to today, net of the remaining fund. It is used to compare offers with one another; it can be negative."], "financer"),
  provision_interne: entree(["Provision interne", "In-house provision"],
    ["Ne rien placer : l'entreprise paie chaque IFC le jour du départ, sur sa trésorerie. Aucun frais, mais aucun rendement et tout le risque.",
     "Investing nothing: the company pays each IFC on the day of departure, out of its cash. No fees, but no return and all of the risk."], "financer"),
  courtage: entree(["Courtage", "Brokerage"],
    ["Le service de la plateforme : votre courtier, mandaté par vous, place le contrat et porte vos prestations auprès de l'assureur. Gratuit pour l'entreprise.",
     "The platform's service: your broker, appointed by you, places the contract and handles your benefit payments with the insurer. Free for the company."], "contrat"),
  mandat: entree(["Mandat de courtage", "Brokerage mandate"],
    ["Le document par lequel l'entreprise charge la plateforme de la représenter auprès des assureurs. Sans mandat, pas de courtage.",
     "The document by which the company appoints the platform to represent it with insurers. No mandate, no brokerage."], "contrat"),
  prise_en_charge: entree(["Dossier de prise en charge", "Claim file"],
    ["En courtage, la demande de paiement d'une indemnité que la plateforme monte, scelle et transmet à l'assureur, puis suit jusqu'au paiement.",
     "Under brokerage, the request for payment of a benefit that the platform prepares, seals and sends to the insurer, then follows until it is paid."], "departs"),
  cahier: entree(["Cahier des charges", "Specifications"],
    ["Le document envoyé aux assureurs : votre engagement, votre régime et vos exigences, sur une base commune — sans aucun nom de salarié.",
     "The document sent to insurers: your obligation, your scheme and your requirements, on a common basis — without a single employee's name."], "cahier"),
  anonymat: entree(["Regroupement anonyme", "Anonymous grouping"],
    ["Dans le cahier des charges, aucune ligne ne décrit moins de trois salariés : on ne peut reconnaître personne.",
     "In the specifications, no line describes fewer than three employees: nobody can be identified."], "cahier"),
  sceau: entree(["Sceau", "Seal"],
    ["L'empreinte signée d'un rapport émis. N'importe qui peut vérifier en ligne qu'un document est l'original, octet pour octet.",
     "The signed fingerprint of an issued report. Anyone can check online that a document is the original, byte for byte."], "verifier"),
  emission: entree(["Émission", "Issue"],
    ["Le moment où le conseiller fige l'étude : elle ne change plus, son rapport est scellé et numéroté.",
     "The moment the adviser freezes the study: it no longer changes, and its report is sealed and numbered."], "etude"),
} satisfies Record<string, Definition>;

export type CleTerme = keyof typeof GLOSSAIRE;
