// Les mots du métier, en une phrase chacun. Une infobulle (<Terme>) et le glossaire du guide lisent ce texte :
// une définition changée ici change partout.

export interface Definition { terme: string; definition: string; chapitre?: string }

export const GLOSSAIRE = {
  ifc: { terme: "IFC", chapitre: "comprendre",
    definition: "Indemnité de fin de carrière : ce que l'employeur verse au salarié qui part en retraite, en mois de salaire, selon son ancienneté et la convention collective ou le régime de l'entreprise." },
  convention: { terme: "Convention collective", chapitre: "conventions",
    definition: "Le texte signé pour une branche (commerce, banques…) qui fixe le barème minimum de l'IFC. C'est le plancher : l'entreprise peut verser plus, jamais moins." },
  regime: { terme: "Régime", chapitre: "regime",
    definition: "Ce que VOTRE entreprise verse réellement : un accord, un usage, les contrats. Il peut être plus généreux que la convention, par catégorie de personnel." },
  plancher: { terme: "Plancher", chapitre: "regime",
    definition: "Le minimum de la convention. À chaque ancienneté, le calcul retient le plus favorable du régime et de la convention." },
  vapf: { terme: "VAPF", chapitre: "comprendre",
    definition: "Valeur actuelle des prestations futures : l'IFC qui sera versée à chaque salarié, ramenée à aujourd'hui, pondérée par les chances qu'il soit encore là et en vie à la retraite." },
  dette: { terme: "Dette actuarielle", chapitre: "comprendre",
    definition: "La part de la VAPF déjà acquise par les années passées dans l'entreprise. C'est l'engagement à la date d'évaluation — ce qu'un assureur doit avoir en caisse pour être à jour." },
  charge: { terme: "Charge annuelle", chapitre: "comprendre",
    definition: "Ce que coûte une année de service de plus : les droits que les salariés acquièrent pendant l'exercice qui vient." },
  fonds: { terme: "Fonds constitué", chapitre: "financer",
    definition: "L'argent déjà placé chez un assureur pour vos IFC. Il vous appartient et se retranche de ce qu'il reste à verser." },
  cotisation_nette: { terme: "Cotisation nette", chapitre: "comprendre",
    definition: "Dette + charge − fonds : ce qu'il manque pour être à jour, avant les frais de l'assureur. Nulle si le fonds couvre déjà tout." },
  frais_cotisation: { terme: "Frais sur cotisation", chapitre: "financer",
    definition: "La part de chaque versement que l'assureur garde pour sa gestion (4 % par défaut dans l'étude). La cotisation à verser = cotisation nette + ces frais." },
  cotisation: { terme: "Cotisation à verser", chapitre: "comprendre",
    definition: "Le montant à verser à l'assureur, frais compris, pour que le fonds couvre la dette et la charge de l'année." },
  actualisation: { terme: "Taux d'actualisation", chapitre: "comprendre",
    definition: "Le taux qui ramène à aujourd'hui une somme payée dans des années. Plus il est haut, plus la dette paraît petite : c'est l'hypothèse la plus sensible." },
  croissance: { terme: "Croissance des salaires", chapitre: "comprendre",
    definition: "La hausse annuelle supposée des salaires jusqu'à la retraite. L'IFC se calcule sur le salaire de fin de carrière, pas celui d'aujourd'hui." },
  turnover: { terme: "Rotation du personnel", chapitre: "comprendre",
    definition: "La probabilité qu'un salarié quitte l'entreprise avant la retraite (démission, licenciement). Un départ avant la retraite ne coûte pas d'IFC." },
  mortalite: { terme: "Table de mortalité", chapitre: "comprendre",
    definition: "Les probabilités de survie à chaque âge. L'étude utilise la table réglementaire CIMA (TV CIMA F)." },
  anciennete: { terme: "Ancienneté", chapitre: "personnel",
    definition: "Les années passées dans l'entreprise, calculées à partir de la date d'embauche." },
  taux_garanti: { terme: "Taux garanti", chapitre: "financer",
    definition: "Le rendement minimum que l'assureur s'engage à servir sur le fonds, chaque année." },
  participation: { terme: "Participation aux bénéfices", chapitre: "financer",
    definition: "La part des produits financiers au-delà du taux garanti que l'assureur reverse au fonds (par exemple 85 %)." },
  cout_net: { terme: "Coût net actualisé", chapitre: "financer",
    definition: "Ce que coûte une offre sur l'horizon choisi, ramené à aujourd'hui, fonds restant déduit. Il sert à comparer les offres entre elles ; il peut être négatif." },
  provision_interne: { terme: "Provision interne", chapitre: "financer",
    definition: "Ne rien placer : l'entreprise paie chaque IFC le jour du départ, sur sa trésorerie. Aucun frais, mais aucun rendement et tout le risque." },
  courtage: { terme: "Courtage", chapitre: "contrat",
    definition: "Le service où la plateforme est votre courtier, mandatée par vous : elle place le contrat et porte vos prestations auprès de l'assureur." },
  comparaison: { terme: "Comparaison", chapitre: "contrat",
    definition: "Le service où la plateforme éclaire votre choix d'assureur ; vous contractez et traitez les prestations directement avec lui." },
  mandat: { terme: "Mandat de courtage", chapitre: "contrat",
    definition: "Le document par lequel l'entreprise charge la plateforme de la représenter auprès des assureurs. Sans mandat, pas de courtage." },
  prise_en_charge: { terme: "Dossier de prise en charge", chapitre: "departs",
    definition: "En courtage, la demande de paiement d'une indemnité que la plateforme monte, scelle et transmet à l'assureur, puis suit jusqu'au paiement." },
  cahier: { terme: "Cahier des charges", chapitre: "cahier",
    definition: "Le document envoyé aux assureurs : votre engagement, votre régime et vos exigences, sur une base commune — sans aucun nom de salarié." },
  anonymat: { terme: "Regroupement anonyme", chapitre: "cahier",
    definition: "Dans le cahier des charges, aucune ligne ne décrit moins de trois salariés : on ne peut reconnaître personne." },
  sceau: { terme: "Sceau", chapitre: "verifier",
    definition: "L'empreinte signée d'un rapport émis. N'importe qui peut vérifier en ligne qu'un document est l'original, octet pour octet." },
  emission: { terme: "Émission", chapitre: "etude",
    definition: "Le moment où le conseiller fige l'étude : elle ne change plus, son rapport est scellé et numéroté." },
} satisfies Record<string, Definition>;

export type CleTerme = keyof typeof GLOSSAIRE;
